apiVersion: apps/v1
kind: Deployment
metadata:
  name: nop-commerce-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nopcommerce
  template:
    metadata:
      labels:
        app: nopcommerce
    spec:
      containers:
        - name: nopcommerce
          image: ghcr.io/gandru123/nop:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
