adminUser: admin
adminPassword: admin123

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: nginx

  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

  hosts:
    - grafana.3.108.7.7.nip.io

  path: /
  pathType: Prefix

  tls: []

persistence:
  enabled: true
  size: 5Gi
  storageClassName: local-path