adminUser: admin
adminPassword: admin123

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: traefik

  hosts:
    - grafana.13.200.4.238.nip.io  

  path: /
  pathType: Prefix

  tls: []

persistence:
  enabled: false