adminUser: admin
adminPassword: admin123

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: traefik

  hosts:
    - grafana.3.7.62.55.nip.io

  path: /
  pathType: Prefix

  tls: []

persistence:
  enabled: false