name: dotnet

on: 
  push:
    branches:
      - develop

jobs:
  dotnet_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.100'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3
        with:
          args: >
            -Dsonar.projectKey=gandru123_nopCommerce
            -Dsonar.organization=jenkins-java
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

      - name: Publish .NET project
        run: dotnet publish -c Release src/Presentation/Nop.Web/Nop.Web.csproj -o gandru

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Docker image to ECR
        env:
          ECR_REGISTRY: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 753916464885.dkr.ecr.ap-south-1.amazonaws.com
          ECR_REPOSITORY: gitactionjava
          IMAGE_TAG: latest
        run: |
          docker build -t gitactionjava .
          docker tag gitactionjava:latest 753916464885.dkr.ecr.ap-south-1.amazonaws.com/gitactionjava:latest
          docker push 753916464885.dkr.ecr.ap-south-1.amazonaws.com/gitactionjava:latest
